### ISSUE TITLE
价格保护运行错误

### ISSUE THREAD

**Issue by binge8** [LingFeng0918/jd_scripts#3]
🔔京东价格保护, 开始!
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /jd/scripts/node_modules/canvas/lib/bindings.js
- /jd/scripts/node_modules/canvas/lib/canvas.js
- /jd/scripts/node_modules/canvas/index.js
- /jd/scripts/node_modules/jsdom/lib/jsdom/utils.js
- /jd/scripts/node_modules/jsdom/lib/jsdom/living/events/MouseEvent-impl.js
- /jd/scripts/node_modules/jsdom/lib/jsdom/living/generated/MouseEvent.js
- /jd/scripts/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js
- /jd/scripts/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js
- /jd/scripts/node_modules/jsdom/lib/jsdom/living/interfaces.js
- /jd/scripts/node_modules/jsdom/lib/jsdom/browser/Window.js
- /jd/scripts/node_modules/jsdom/lib/api.js
- /jd/scripts/jd_priceProtect.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/jd/scripts/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/jd/scripts/node_modules/canvas/lib/bindings.js',
    '/jd/scripts/node_modules/canvas/lib/canvas.js',
    '/jd/scripts/node_modules/canvas/index.js',
    '/jd/scripts/node_modules/jsdom/lib/jsdom/utils.js',
    '/jd/scripts/node_modules/jsdom/lib/jsdom/living/events/MouseEvent-impl.js',
    '/jd/scripts/node_modules/jsdom/lib/jsdom/living/generated/MouseEvent.js',
    '/jd/scripts/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js',
    '/jd/scripts/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js',
    '/jd/scripts/node_modules/jsdom/lib/jsdom/living/interfaces.js',
    '/jd/scripts/node_modules/jsdom/lib/jsdom/browser/Window.js',
    '/jd/scripts/node_modules/jsdom/lib/api.js',
    '/jd/scripts/jd_priceProtect.js'
  ]
}

**Comment by LingFeng9527** [comment]
重装node
